/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AttorneysRouteImport } from './routes/attorneys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttorneysSlugRouteImport } from './routes/attorneys.$slug'

const AttorneysRoute = AttorneysRouteImport.update({
  id: '/attorneys',
  path: '/attorneys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttorneysSlugRoute = AttorneysSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AttorneysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attorneys': typeof AttorneysRouteWithChildren
  '/attorneys/$slug': typeof AttorneysSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attorneys': typeof AttorneysRouteWithChildren
  '/attorneys/$slug': typeof AttorneysSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attorneys': typeof AttorneysRouteWithChildren
  '/attorneys/$slug': typeof AttorneysSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/attorneys' | '/attorneys/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/attorneys' | '/attorneys/$slug'
  id: '__root__' | '/' | '/attorneys' | '/attorneys/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttorneysRoute: typeof AttorneysRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/attorneys': {
      id: '/attorneys'
      path: '/attorneys'
      fullPath: '/attorneys'
      preLoaderRoute: typeof AttorneysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attorneys/$slug': {
      id: '/attorneys/$slug'
      path: '/$slug'
      fullPath: '/attorneys/$slug'
      preLoaderRoute: typeof AttorneysSlugRouteImport
      parentRoute: typeof AttorneysRoute
    }
  }
}

interface AttorneysRouteChildren {
  AttorneysSlugRoute: typeof AttorneysSlugRoute
}

const AttorneysRouteChildren: AttorneysRouteChildren = {
  AttorneysSlugRoute: AttorneysSlugRoute,
}

const AttorneysRouteWithChildren = AttorneysRoute._addFileChildren(
  AttorneysRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttorneysRoute: AttorneysRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
